#!/usr/bin/env bash
# Gracefully reloads Gunicorn.

if pgrep gunicorn >/dev/null; then
    pgrep gunicorn | xargs kill -HUP
    sleep 2

    if pgrep gunicorn >/dev/null; then
        echo "OK: Gunicorn reloaded successfully."
    else
        echo "NOk: Failed to reload Gunicorn."
    fi
else
    echo "NOk: Gunicorn process not found."
fi
